In [6]:

import numpy as np
import pandas as pd

In [7]:
data = pd.read_csv('Week2_data.csv')

data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [8]:

data['Throughput'] = (data['Total DL (Bytes)'] + data['Total UL (Bytes)']) / data['Dur. (ms)']
top_throughput = data['Throughput'].nlargest(10)
bottom_throughput = data['Throughput'].nsmallest(10)
most_frequent_throughput = data['Throughput'].value_counts().nlargest(10)
print("Top 10 Throughput Values:\n", top_throughput)
print("Bottom 10 Throughput Values:\n", bottom_throughput)
print("Most Frequent 10 Throughput Values:\n", most_frequent_throughput)

Top 10 Throughput Values:
 24978    120044.093729
24675    117102.909561
24678    115274.125241
24359    113665.780478
24763    112529.522195
24027    111616.689896
24716    111387.998901
24941    110822.562361
24284    108193.051596
24189    105725.420593
Name: Throughput, dtype: float64
Bottom 10 Throughput Values:
 100003     54.775569
25010      83.790653
25061      89.025857
25008      91.426180
100042     93.560778
125090     94.473518
125022     97.026649
50005     101.108476
125053    103.263813
50057     106.360183
Name: Throughput, dtype: float64
Most Frequent 10 Throughput Values:
 Throughput
7736.361024    1
7944.152899    1
8163.718179    1
2459.091815    1
1900.413165    1
1783.673878    1
7514.588173    1
1681.550235    1
3269.849502    1
3942.744627    1
Name: count, dtype: int64

In [1]:
!pip install dash-bootstrap-components

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/dash-bootstrap-components/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/dash-bootstrap-components/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/dash-bootstrap-components/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/dash-bootstrap-components/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/dash-bootstrap-components/
ERROR: Could not find a version that satisfies the requirement dash-bootstrap-components (from versions: none)
ERROR: No matching distribution found for dash-bootstrap-components

In [9]:
# Assuming you have start and end times in milliseconds
data['Start'] = pd.to_datetime(data['Start'])
data['End'] = pd.to_datetime(data['End'])

# Compute RTT as the difference between end and start times
data['RTT'] = (data['End'] - data['Start']).dt.total_seconds() * 1000  # Convert seconds to milliseconds

# Compute average RTT
average_rtt = data['RTT'].mean()

print(f'Average RTT: {average_rtt}')

Average RTT: 104609086.4

In [10]:
# Ensure these columns exist
if 'Packet_Loss' in data.columns:
    average_packet_size = 1500  

    data['Total_Packets_Sent'] = (data['Total DL (Bytes)'] + data['Total UL (Bytes)']) / average_packet_size
    data['Estimated_Retransmissions'] = data['Total_Packets_Sent'] * (data['Packet_Loss'] / 100)

    average_retransmission = data['Estimated_Retransmissions'].mean()

    print(f'Average Estimated TCP Retransmission Rate: {average_retransmission}')
else:
    print('Packet_Loss column is missing in the dataset.')

Packet_Loss column is missing in the dataset.